### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by pyros2097** [nstogner/httpware#1]
I see that in each middleware you can return an error but how do I handle any of these errors that happen? Is there a default error handler like in echo https://github.com/labstack/echo or does it have to be the first middleware that handles all errors?

**Comment by nstogner** [comment]
Hey, it used to be in a middleware package "errorware" but I recently moved it to the base package "httpware". Errors are handled when you call the Then(...) or ThenFunc(...) methods after composing middleware together using the httpware.Compose(...) function. I will put this in the docs. What is your opinion on the best place for error management code to go?

**Comment by pyros2097** [comment]
Well it seemed a bit weird when I tried out the example and forcefully returned an error and I automatically got an internal server error. I think maybe the error handler should be customizable and people should implictly declare to use it (instead of it happening after then). Maybe having and global or a per middleware group error handler might be useful in this case like this https://labstack.com/echo/guide/customization#http-error-handler and also a default panic handler will also be good.

**Comment by nstogner** [comment]
Thanks for the feedback.

So a little background...

I used to have it so that middleware could declare dependencies on other middleware. The Compose(...) function was called MustCompose(...) and would check for these dependencies so that you wouldn't get unexpected nil-pointers when running the server if you forgot to include some needed middleware in your chain. I eventually removed this dependency concept in order to simplify things and also make it easier to incorporate 3rd party middleware.

When I removed dependency checking and changed a little bit of middleware code, the one thing that was left over was error handling. Packages such as tokenware were dependent on packages like errorware for catching their non-nil errors and sending 401-Unauthorized responses. I didn't want the case to happen where someone could forget to include errorware and all of a sudden unauthorized requests were going thru. So I figured I would move error management to the top-most level (httpware), and have it on by default.

So now I am thinking that there are a few different options:
1. Include error handling by default (as-is) and add an option to configure/swap it out with another error handler.
2. Force the user to declare an error handler explicitly when they are composing middleware, and provide a middleware package (errorware) that they can easily choose and configure (or bring their own)

Option 1 has the drawback of implicitly doing something that might be unexpected. Option 2 has the drawback of including an additional setup step for the user. I am leaning toward option 2 because I have tried to ensure that all of the other parts of using middleware are very explicit (one of the reasons why I gravitate toward "middleware" over "frameworks").

It sounds like you like option 2?

**Comment by pyros2097** [comment]
Yeah option 2 seems like what I was talking about and is what I think is better. Since we switched to graphql we didn't need a router anymore so initially I was doing everything is a single req, res callback and checking paths, logging, errorhandling but then that became too complicated. So then we switchted to echo (which had error handling in built which is very important to us) as it made it more composable but then had too much other stuff which we aren't using and then I found httpware which was one of the middleware composers which also had error handling and thought of replacing echo with it (plus we get performance benefits).

**Comment by nstogner** [comment]
I am the process of coding it up. I think the best place to put the explicit error handler is as the first argument in the Compose function:
```go
m := httpware.Compose(
  httpware.DefaultErrHandler,
  contentware.New(contentware.Defaults)
  ...
)
```
I should have the commits out soon. I am glad you are looking at this library as an option for your team. I will just give you a word of caution though: the API isn't quite stable yet (as this thread shows).

Let me know if there is anything else that you think needs changing/clarification.

**Comment by nstogner** [comment]
See commit https://github.com/nstogner/httpware/commit/3f237d40551b7f0ffa648dd4bf0e7f718e1e802b

I will open another ticket for adding panic recovery.
